server:
  port: 8002

spring:
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      #빌드 될때마다 DB 초기화
        ddl-auto: update
        #query문 정렬해서 보여주기
        format_sql : true
    database-platform: org.hibernate.dialect.MariaDB103Dialect
#DB 정보
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/testschemas
    username: root
    password: 1234
#타입리프 캐시 설정
  thymeleaf :
    cache: false

logging:
  level:
    org:
      hibernate:
        #DB 값을 로그로 보여준다
        SQL: DEBUG
        #???값으로 설정된 DB 값들 보여주기
        type.descriptor.sql.BasicBinder: TRACE